version: '3.8'

services:
postgres:
  image: postgres:latest
  container_name: postgres
  environment:
    POSTGRES_USER: myuser
    POSTGRES_PASSWORD: mypassword
    POSTGRES_DB: mydatabase
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data

  app:
    container_name: my_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydatabase
    depends_on:
      - postgres
